apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
      - name: jenkins-app
        image: hyosim1996/jenkins-docker-example:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-app-service
  namespace: default
spec:
  selector:
    app: jenkins-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
